interface SeedRecipe {
  title: string;
  description?: string;
  ingredients: { name: string; quantity?: number; unit?: string }[];
  steps: string[];
  cuisine?: string;
  difficulty: 'easy' | 'medium' | 'hard';
  cookingTimeMinutes: number;
  servings: number;
  dietaryTags?: string[];
  imageUrl?: string;
  // no nutrition: AiService will estimate
}

export const recipeSeedData: SeedRecipe[] = [
  {
    title: 'Margherita Pizza',
    description: 'Classic Italian pizza with tomato, mozzarella, and basil.',
    ingredients: [
      { name: 'pizza dough', quantity: 1, unit: 'base' },
      { name: 'tomato sauce', quantity: 100, unit: 'g' },
      { name: 'mozzarella', quantity: 125, unit: 'g' },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      { name: 'basil leaves', quantity: 6, unit: 'pcs' },
    ],
    steps: [
      'Preheat oven to 250°C.',
      'Spread tomato sauce on pizza dough.',
      'Add mozzarella slices and basil leaves.',
      'Drizzle with olive oil and bake until crust is golden.',
    ],
    cuisine: 'Italian',
    difficulty: 'medium',
    cookingTimeMinutes: 20,
    servings: 2,
    dietaryTags: ['vegetarian'],
  },
  {
    title: 'Simple Tomato Pasta',
    description: 'Quick pasta in a garlicky tomato sauce.',
    ingredients: [
      { name: 'pasta', quantity: 200, unit: 'g' },
      { name: 'tomato', quantity: 3, unit: 'pcs' },
      { name: 'garlic', quantity: 3, unit: 'cloves' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'salt', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      'Boil pasta until al dente.',
      'Sauté garlic in olive oil.',
      'Add chopped tomatoes and cook until soft.',
      'Toss pasta in the sauce and season with salt.',
    ],
    cuisine: 'Italian',
    difficulty: 'easy',
    cookingTimeMinutes: 20,
    servings: 2,
    dietaryTags: ['vegetarian'],
  },
  {
    title: 'Chana Masala',
    description: 'Indian chickpea curry with spices.',
    ingredients: [
      { name: 'chickpeas', quantity: 200, unit: 'g' },
      { name: 'onion', quantity: 1, unit: 'pc' },
      { name: 'tomato', quantity: 2, unit: 'pcs' },
      { name: 'ginger', quantity: 1, unit: 'inch' },
      { name: 'garlic', quantity: 3, unit: 'cloves' },
      { name: 'chili powder', quantity: 1, unit: 'tsp' },
      { name: 'garam masala', quantity: 1, unit: 'tsp' },
      { name: 'oil', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      'Soak and boil chickpeas until tender.',
      'Sauté onion, ginger, and garlic.',
      'Add chopped tomatoes and spices.',
      'Simmer with chickpeas until flavors combine.',
    ],
    cuisine: 'Indian',
    difficulty: 'medium',
    cookingTimeMinutes: 40,
    servings: 3,
    dietaryTags: ['vegan', 'gluten-free'],
  },
  {
    title: 'Paneer Butter Masala',
    description: 'Rich North Indian curry with paneer in a creamy tomato sauce.',
    ingredients: [
      { name: 'paneer', quantity: 200, unit: 'g' },
      { name: 'butter', quantity: 2, unit: 'tbsp' },
      { name: 'cream', quantity: 50, unit: 'ml' },
      { name: 'tomato', quantity: 3, unit: 'pcs' },
      { name: 'onion', quantity: 1, unit: 'pc' },
      { name: 'garam masala', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      'Sauté onion and tomato in butter.',
      'Blend to a smooth gravy.',
      'Add paneer cubes, cream, and garam masala.',
      'Simmer briefly and serve hot.',
    ],
    cuisine: 'Indian',
    difficulty: 'medium',
    cookingTimeMinutes: 30,
    servings: 3,
    dietaryTags: ['vegetarian', 'gluten-free'],
  },
  {
    title: 'Vegetable Stir-Fry',
    description: 'Colorful mixed vegetables in a light soy sauce.',
    ingredients: [
      { name: 'broccoli', quantity: 100, unit: 'g' },
      { name: 'carrot', quantity: 1, unit: 'pc' },
      { name: 'bell pepper', quantity: 1, unit: 'pc' },
      { name: 'soy sauce', quantity: 2, unit: 'tbsp' },
      { name: 'garlic', quantity: 2, unit: 'cloves' },
      { name: 'oil', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      'Heat oil in a wok.',
      'Add garlic and sauté briefly.',
      'Add chopped vegetables and stir-fry on high heat.',
      'Add soy sauce and toss until veggies are crisp-tender.',
    ],
    cuisine: 'Asian',
    difficulty: 'easy',
    cookingTimeMinutes: 15,
    servings: 2,
    dietaryTags: ['vegan'],
  },
  {
    title: 'Vegan Buddha Bowl',
    description: 'Nourishing bowl with quinoa, roasted veggies, and chickpeas.',
    ingredients: [
      { name: 'quinoa', quantity: 100, unit: 'g' },
      { name: 'sweet potato', quantity: 1, unit: 'pc' },
      { name: 'chickpeas', quantity: 100, unit: 'g' },
      { name: 'spinach', quantity: 50, unit: 'g' },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      'Cook quinoa according to package instructions.',
      'Roast cubed sweet potato and chickpeas with olive oil.',
      'Assemble bowl with quinoa, roasted veggies, and spinach.',
    ],
    cuisine: 'Fusion',
    difficulty: 'easy',
    cookingTimeMinutes: 30,
    servings: 2,
    dietaryTags: ['vegan', 'gluten-free'],
  },
  {
    title: 'Grilled Chicken Salad',
    description: 'Light salad with grilled chicken and mixed greens.',
    ingredients: [
      { name: 'chicken breast', quantity: 200, unit: 'g' },
      { name: 'lettuce', quantity: 50, unit: 'g' },
      { name: 'tomato', quantity: 1, unit: 'pc' },
      { name: 'cucumber', quantity: 0.5, unit: 'pc' },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      { name: 'lemon juice', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      'Grill seasoned chicken breast until cooked.',
      'Chop vegetables and arrange on a plate.',
      'Slice chicken and place over greens.',
      'Drizzle with olive oil and lemon juice.',
    ],
    cuisine: 'International',
    difficulty: 'easy',
    cookingTimeMinutes: 25,
    servings: 2,
    dietaryTags: ['gluten-free'],
  },
  {
    title: 'Overnight Oats',
    description: 'No-cook oats soaked in milk with fruits and nuts.',
    ingredients: [
      { name: 'rolled oats', quantity: 60, unit: 'g' },
      { name: 'milk', quantity: 150, unit: 'ml' },
      { name: 'banana', quantity: 1, unit: 'pc' },
      { name: 'chia seeds', quantity: 1, unit: 'tbsp' },
      { name: 'nuts', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      'Combine oats, milk, and chia seeds in a jar.',
      'Refrigerate overnight.',
      'Top with sliced banana and nuts to serve.',
    ],
    cuisine: 'Breakfast',
    difficulty: 'easy',
    cookingTimeMinutes: 10,
    servings: 1,
    dietaryTags: ['vegetarian'],
  },
  {
    title: 'Avocado Toast',
    description: 'Toasted bread topped with mashed avocado and seasoning.',
    ingredients: [
      { name: 'bread', quantity: 2, unit: 'slices' },
      { name: 'avocado', quantity: 1, unit: 'pc' },
      { name: 'salt', quantity: 0.5, unit: 'tsp' },
      { name: 'pepper', quantity: 0.25, unit: 'tsp' },
      { name: 'lemon juice', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      'Toast the bread slices.',
      'Mash avocado with salt, pepper, and lemon juice.',
      'Spread mixture on toast and serve.',
    ],
    cuisine: 'Breakfast',
    difficulty: 'easy',
    cookingTimeMinutes: 10,
    servings: 1,
    dietaryTags: ['vegan'],
  },
  {
    title: 'Dal Tadka',
    description: 'Yellow lentils with a tempered spice tadka.',
    ingredients: [
      { name: 'yellow lentils', quantity: 150, unit: 'g' },
      { name: 'onion', quantity: 1, unit: 'pc' },
      { name: 'tomato', quantity: 1, unit: 'pc' },
      { name: 'garlic', quantity: 3, unit: 'cloves' },
      { name: 'ghee', quantity: 1, unit: 'tbsp' },
      { name: 'cumin seeds', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      'Boil lentils until soft.',
      'Sauté onion, garlic, and tomato in ghee.',
      'Add cumin seeds and spices.',
      'Pour tadka over boiled dal and simmer briefly.',
    ],
    cuisine: 'Indian',
    difficulty: 'easy',
    cookingTimeMinutes: 35,
    servings: 3,
    dietaryTags: ['vegetarian', 'gluten-free'],
  },
  {
    title: 'Chicken Biryani',
    description: 'Layered rice dish with spiced chicken.',
    ingredients: [
      { name: 'basmati rice', quantity: 200, unit: 'g' },
      { name: 'chicken', quantity: 250, unit: 'g' },
      { name: 'onion', quantity: 2, unit: 'pcs' },
      { name: 'yogurt', quantity: 50, unit: 'g' },
      { name: 'biryani masala', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      'Marinate chicken in yogurt and spices.',
      'Parboil rice.',
      'Layer chicken and rice in a pot.',
      'Cook on low heat until chicken and rice are fully done.',
    ],
    cuisine: 'Indian',
    difficulty: 'hard',
    cookingTimeMinutes: 60,
    servings: 4,
    dietaryTags: [],
  },
  {
    title: 'Greek Salad',
    description: 'Refreshing salad with cucumber, tomato, feta, and olives.',
    ingredients: [
      { name: 'cucumber', quantity: 1, unit: 'pc' },
      { name: 'tomato', quantity: 2, unit: 'pcs' },
      { name: 'feta cheese', quantity: 50, unit: 'g' },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      { name: 'olives', quantity: 10, unit: 'pcs' },
    ],
    steps: [
      'Chop cucumber and tomatoes.',
      'Crumble feta cheese.',
      'Combine all ingredients and drizzle with olive oil.',
    ],
    cuisine: 'Mediterranean',
    difficulty: 'easy',
    cookingTimeMinutes: 10,
    servings: 2,
    dietaryTags: ['vegetarian', 'gluten-free'],
  },
  {
    title: 'Lemon Garlic Salmon',
    description: 'Baked salmon fillets with lemon and garlic.',
    ingredients: [
      { name: 'salmon fillet', quantity: 200, unit: 'g' },
      { name: 'lemon', quantity: 0.5, unit: 'pc' },
      { name: 'garlic', quantity: 2, unit: 'cloves' },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      { name: 'salt', quantity: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 200°C.',
      'Place salmon on baking tray.',
      'Top with minced garlic, lemon slices, olive oil, and salt.',
      'Bake until salmon is cooked through.',
    ],
    cuisine: 'International',
    difficulty: 'easy',
    cookingTimeMinutes: 20,
    servings: 2,
    dietaryTags: ['gluten-free'],
  },
  {
    title: 'Veg Fried Rice',
    description: 'Stir-fried rice with mixed vegetables and soy sauce.',
    ingredients: [
      { name: 'rice', quantity: 200, unit: 'g' },
      { name: 'carrot', quantity: 1, unit: 'pc' },
      { name: 'peas', quantity: 50, unit: 'g' },
      { name: 'bell pepper', quantity: 1, unit: 'pc' },
      { name: 'soy sauce', quantity: 2, unit: 'tbsp' },
      { name: 'oil', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      'Cook rice and let it cool.',
      'Stir-fry chopped vegetables in oil.',
      'Add rice and soy sauce, and toss on high heat.',
    ],
    cuisine: 'Asian',
    difficulty: 'easy',
    cookingTimeMinutes: 25,
    servings: 3,
    dietaryTags: ['vegan'],
  },
  {
    title: 'Palak Paneer',
    description: 'Indian curry with paneer in a spinach gravy.',
    ingredients: [
      { name: 'spinach', quantity: 200, unit: 'g' },
      { name: 'paneer', quantity: 150, unit: 'g' },
      { name: 'onion', quantity: 1, unit: 'pc' },
      { name: 'tomato', quantity: 1, unit: 'pc' },
      { name: 'garlic', quantity: 3, unit: 'cloves' },
      { name: 'cream', quantity: 30, unit: 'ml' },
    ],
    steps: [
      'Blanch spinach and blend to a puree.',
      'Sauté onion, tomato, and garlic.',
      'Add spinach puree and paneer cubes.',
      'Finish with cream and simmer briefly.',
    ],
    cuisine: 'Indian',
    difficulty: 'medium',
    cookingTimeMinutes: 35,
    servings: 3,
    dietaryTags: ['vegetarian', 'gluten-free'],
  },
  {
    title: 'Pancakes',
    description: 'Fluffy pancakes served with syrup.',
    ingredients: [
      { name: 'flour', quantity: 150, unit: 'g' },
      { name: 'milk', quantity: 200, unit: 'ml' },
      { name: 'egg', quantity: 1, unit: 'pc' },
      { name: 'baking powder', quantity: 1, unit: 'tsp' },
      { name: 'sugar', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      'Whisk together flour, baking powder, and sugar.',
      'Add milk and egg to form batter.',
      'Cook spoonfuls of batter on a greased pan until golden.',
    ],
    cuisine: 'Breakfast',
    difficulty: 'easy',
    cookingTimeMinutes: 20,
    servings: 2,
    dietaryTags: ['vegetarian'],
  },
  {
    title: 'Hummus & Pita',
    description: 'Creamy chickpea hummus served with warm pita bread.',
    ingredients: [
      { name: 'chickpeas', quantity: 150, unit: 'g' },
      { name: 'tahini', quantity: 2, unit: 'tbsp' },
      { name: 'lemon juice', quantity: 1, unit: 'tbsp' },
      { name: 'garlic', quantity: 1, unit: 'clove' },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      { name: 'pita bread', quantity: 2, unit: 'pcs' },
    ],
    steps: [
      'Blend chickpeas, tahini, lemon juice, garlic, and olive oil.',
      'Adjust seasoning and texture with water if needed.',
      'Serve with warm pita bread.',
    ],
    cuisine: 'Middle Eastern',
    difficulty: 'easy',
    cookingTimeMinutes: 15,
    servings: 2,
    dietaryTags: ['vegan'],
  },
  {
    title: 'Masala Omelette',
    description: 'Spiced Indian-style omelette.',
    ingredients: [
      { name: 'egg', quantity: 2, unit: 'pcs' },
      { name: 'onion', quantity: 0.5, unit: 'pc' },
      { name: 'tomato', quantity: 0.5, unit: 'pc' },
      { name: 'green chili', quantity: 1, unit: 'pc' },
      { name: 'oil', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      'Beat eggs with chopped onion, tomato, and chili.',
      'Pour mixture onto a hot greased pan.',
      'Cook until set on both sides.',
    ],
    cuisine: 'Indian',
    difficulty: 'easy',
    cookingTimeMinutes: 10,
    servings: 1,
    dietaryTags: ['gluten-free'],
  },
  {
    title: 'Minestrone Soup',
    description: 'Hearty Italian vegetable soup with beans and pasta.',
    ingredients: [
      { name: 'onion', quantity: 1, unit: 'pc' },
      { name: 'carrot', quantity: 1, unit: 'pc' },
      { name: 'celery', quantity: 1, unit: 'stalk' },
      { name: 'tomato', quantity: 2, unit: 'pcs' },
      { name: 'beans', quantity: 100, unit: 'g' },
      { name: 'small pasta', quantity: 50, unit: 'g' },
    ],
    steps: [
      'Sauté onion, carrot, and celery.',
      'Add tomatoes, beans, and water or stock.',
      'Simmer until vegetables are tender.',
      'Add pasta and cook until al dente.',
    ],
    cuisine: 'Italian',
    difficulty: 'medium',
    cookingTimeMinutes: 40,
    servings: 4,
    dietaryTags: ['vegetarian'],
  },
];

export default recipeSeedData;
